name: CI
on:
  pull_request:
    branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check

      - name: Run automated tests
        run: npm run test:ci

      - name: Upload code coverage as an artefact
        run: npm test -- --coverage
        env:
          CI: true




